apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: hussainbeecmd/devx-devops-pipeline
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-svc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8080       # Port exposed by the Service
      targetPort: 8080 # Port on the container
  type: NodePort
